Adding reviews
sbeleidy/peerbots-content pull request #65
Opened 2021-12-30 21:00 UTC by sbeleidy

2021-12-30 23:21 UTC, ynadeem commented on pages/content/[contentId].js
> +      console.log("User and purchased content");
Remove the console.log

2021-12-30 23:22 UTC, ynadeem commented on pages/content/[contentId].js
> +        console.log(newReview);
Remove console.log

2021-12-31 17:57 UTC, ynadeem commented on pages/content/[contentId].js
> +                      value={review.data.rating}
Can this be rounded to 1 or 2 decimal places? We don't want to render a rating of 3.666666666666667 stars to the user. Did some quick searching on Google and this screenshot seems to be the accepted solution:

![image](https://user-images.githubusercontent.com/7433102/147834780-bf464a70-a648-4971-8d2e-1d07bfe3c7b5.png)

2021-12-31 17:57 UTC, ynadeem requested changes
Please review my comments

2021-12-31 17:59 UTC, sbeleidy commented on pages/content/[contentId].js
> +                      value={review.data.rating}
Lol why not send me a link? This is super copy pastable 😛 
I'll do some variation of this. I'll also apply it to everywhere we use ratings

2021-12-31 19:43 UTC, ynadeem approved these changes
Looks great!

2021-12-31 19:44 UTC, merged